replicaCount: 1

namespace: monitoring

rbac:
  create: true

image:
  repository: prom/prometheus
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "prometheus"
fullnameOverride: "prometheus"

prometheusArgs:
  - "--storage.tsdb.retention.time=730h"
  - "--config.file=/etc/prometheus/prometheus.yml"
  - "--storage.tsdb.path=/prometheus/"

serviceAccount:
  create: true
  annotations: {}
  name: ""

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  type: ClusterIP
  name: prometheus
  protocol: TCP
  port: 9090
  targetPort: 9090

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /federate
          pathType: Prefix
  tls: []

resources: {}

volumeMounts:
  - name: prometheus-config
    mountPath: /etc/prometheus
  - name: prometheus-storage
    mountPath: /prometheus/

volumes:
  - name: prometheus-config
    configMap:
      defaultMode: 420
      name: prometheus-config
  - name: prometheus-storage
    emptyDir: {}