{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  name: {{ include "prometheus.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}