{{- if .Values.serviceAccounts.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.serviceAccounts.server.annotations | indent 4 }}
{{- end }}